spring.application.name=PetalsNPosies
spring.datasource.url=jdbc:postgresql://localhost:5432/petalsnposies
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

stripe.secret.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=victortran16@gmail.com	
spring.mail.password=cpsy oaqa owlm qabm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true